spring:
  application:
    name: plant-finder
  profiles:
    include: private
  data:
    mongodb:
      uri: mongodb+srv://jihak:MKhhL7Wnu4lVxd3e@cluster0.kv5caik.mongodb.net/mintoDB?retryWrites=true&w=majority